name: petadoption
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_categories_slide/
    - assets/images/home_pets_slide/
    - assets/images/splash_screen/
