// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
// /// // ...
// await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHK2etHLgN6b9V0OYzbDEJC9LZFE_O3fY',
    appId: '1:430536845356:android:6d93842ea2cabb134a8989',
    messagingSenderId: '430536845356',
    projectId: 'petta-app',
    databaseURL: 'https://petta-app-default-rtdb.firebaseio.com',
    storageBucket: 'petta-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4CUiHLFKGRHzzRmHD_6AGubkPy12M6Ro',
    appId: '1:430536845356:ios:c6785d990d77bdae4a8989',
    messagingSenderId: '430536845356',
    projectId: 'petta-app',
    databaseURL: 'https://petta-app-default-rtdb.firebaseio.com',
    storageBucket: 'petta-app.appspot.com',
    iosClientId:
        '430536845356-dbpcagjobpcdj86lhhsd1a6459h5cdsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.petadoption',
  );
}
